# Inserts a blank line between shell prompts
add_newline = true

format = '''$all'''

right_format = "$time"

[directory]
disabled = false
truncation_length = 8
truncation_symbol = 'â€¦/'

[line_break]
disabled = false

[battery]
disabled = false
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 30
style = 'bold red'

[cmd_duration]
min_time = 500
format = 'duration [$duration](bold yellow) '

[git_commit]
tag_symbol = 'ğŸ”– '
only_detached = false
commit_hash_length = 10

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.local'
disabled = false

[time]
disabled = false
time_format = '%T'
style = "bold bright-black"
format = "[$time]($style)"

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true




# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# [character]
# success_symbol = "[>](bold green)"
# error_symbol = "[>](bold red)"

